# Generated by Django 5.0.6 on 2024-06-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='city',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classname',
            name='teacherName',
        ),
        migrations.AddField(
            model_name='student',
            name='className',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classname'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=100)),
                ('className', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.classname')),
            ],
        ),
    ]
