# Generated by Django 5.0.6 on 2024-06-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_classname_city_remove_classname_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classname'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='className',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classname'),
        ),
    ]
