# Generated by Django 5.0.6 on 2024-06-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_classname_alter_teacher_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacherName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
