# Generated by Django 5.0.6 on 2024-06-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_teachername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacherName',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.classname'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='className',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.classname'),
        ),
    ]
