# Generated by Django 5.0.6 on 2024-06-29 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_student_teachername_student_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.classname'),
        ),
    ]
