# Generated by Django 5.0.6 on 2024-06-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_student_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='className',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
